include: package:flutter_lints/flutter.yaml

linter:
  rules:
    file_names: false
    empty_catches: false
    prefer_const_constructors: false
    constant_identifier_names: false
    depend_on_referenced_packages: false
    use_build_context_synchronously: false
    library_private_types_in_public_api: false
    use_full_hex_values_for_flutter_colors: false
    prefer_const_literals_to_create_immutables: false