name: heartmonitor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  share: ^2.0.4
  intl: ^0.19.0
  dartz: ^0.10.1
  get_it: ^8.0.0
  rxdart: ^0.27.7
  provider: ^6.1.2
  equatable: ^2.0.5
  qr_flutter: ^4.1.0
  vector_math: ^2.1.4
  image_picker: ^1.0.4
  package_info: ^2.0.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cupertino_icons: ^1.0.8
  qr_code_scanner: ^1.0.1
  percent_indicator: ^4.2.3
  freezed_annotation: ^2.4.1
  shared_preferences: ^2.3.2
  firebase_database: ^11.1.4
  firebase_analytics: ^11.3.3
  firebase_messaging: ^15.1.3
  cached_network_image: ^3.4.1
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/qr.png
    - assets/logo.png
    - assets/prof.png
    - assets/cover.jpg